test_1_geo_sock_update/config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  get 'chats/room'
  get 'sessions/new'
  get 'sessions/create'

  get "videos/map"
  
  get "messages/read/:id(.:format)" => "messages#read"
  post "messages/read/:id(.:format)" => "messages#read"
  
  
  get '/login' => 'sessions#new'#, #:as => :login
  post '/login' => 'sessions#create'#, #:as => :login
  
  get '/chatroom' => 'chats#room'#, :as => :chat
  post '/chatroom' => 'chats#room'#, :as => :chat
  
  
  get '/redis-messages/:key(.:format)' => 'redis_messages#show'
  delete '/redis-messages/:key(.:format)' => 'redis_messages#destroy'
  post '/redis-messages' => 'redis_messages#create'
  post '/redis-messages/read' => 'redis_messages#read'

  
  resources :messages
  resources :videos
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :media_contents, only: [:create]
  

  root 'chats#room'

end

test_1_geo_sock_update/app/models/video.rb
class Video < ActiveRecord::Base
end

test_1_geo_sock_update/app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  include VideosHelper
  
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  
  # init realtime controller using redis - realtime gem
  realtime_controller({:queue => :redis}) # instruct all requests to enable realtime support via redis
  
  
  #
  # We need override this function (in gem realtime) for only send update notify to target 
  # that view video with video_id (not all viewers)
  #
  def store_realtime_session_redis
      # store session data or any authentication data you want here, generate to JSON data
      old_session_data_str = RedisWrapper.redis.hget("rtSession-" + realtime_user_id.to_s, @realtime_token)
      video_id = (@video_is_loading_id || -1).to_i
      session_data = {
            "user_id" => realtime_user_id,
      }
      
      if !old_session_data_str.nil?
        old_session_data = JSON.parse(old_session_data_str)
      end
      
      
      session_data[:video_ids] = if old_session_data_str.nil? || 
                                     !old_session_data.kind_of?(Hash) ||
                                     old_session_data.key?(:video_ids) ||
                                     !old_session_data["video_ids"].kind_of?(Array) 
                                      [video_id,]
                                    else
                                      old_session_data["video_ids"].push(video_id)
                                    end
      

      # todo: merge additional session data passed in
      
      stored_session_data = JSON.generate(session_data)

      RedisWrapper.redis.hset(
        "rtSession-" + realtime_user_id.to_s,
        @realtime_token,
        stored_session_data,
      )
      
      # expire this realtime session after one day.
      RedisWrapper.redis.expire("rtSession-" + realtime_user_id.to_s, 86400)
  end
  
  def map
    # find the video
    @video_is_loading_id = params[:id]
    @video = Video.find(params[:id].to_i)
  end

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    
    # check if this viewer watch this video before ?!
    unique_viewer = is_unique_viewer @video.id
    
    # location check
    latitude = (params[:lat] || 45.0).to_f
    longitude = (params[:lon] || 4.0).to_f
    
    
    @video_is_loading_id = @video.id
    @video.view += 1
    @video.unique_view = (@video.unique_view || 0) + 1 if unique_viewer  # we should sure unique value not nil value
    @video.save()
    
    # notify to realtime server to push notification to viewer who is viewing this video.
    $redis.publish 'realtime_msg', {msg: "video_views_increase", unique_viewer: unique_viewer, lat: latitude, lon: longitude, recipient_user_ids: [42,], video_id: @video.id}.to_json
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end
  

  def realtime_user_id
    return 42 # if using devise, change this to current_user.id
  end

  
  def realtime_server_url
    # point this to your node.js-socket.io-redis/zmq realtime server (you can set this later)
    @realtime_server_url = 'http://localhost:5001'
    return 'http://localhost:5001'
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :url, :lat, :lon, :view)
    end
end

test_1_geo_sock_update/app/helpers/videos_helper.rb
module VideosHelper
    
  # We will check if this is unique visitor and put some information for later check.
  def is_unique_viewer(current_video_id)
    last_view = JSON.parse(cookies[:last_view].nil? ? "[]" : cookies[:last_view]);
    
    # Check if this user viewed this video ? if not then add video_id to viewed list.
    if last_view.kind_of?(Array) && last_view.include?(current_video_id.to_i)
      return false
    else
      if !last_view.kind_of?(Array)                         # for the first time init or not expected value.
        last_view = [current_video_id.to_i]
      else                                                  # if all okie, just add it.
        last_view = last_view.push(current_video_id.to_i)
        last_view.shift if last_view.count > 100            # we only save last 100 viewed videos
      end
    end
    
    # Unique it? No need because if it include in last view list... it will be returned from above code block
    cookies[:last_view] = JSON.generate(last_view)
    return true
    
  end
  
end

test_1_geo_sock_update/app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  
  
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Youtube Id</label>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :lat %>
    <%= f.text_field :lat, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :lon %>
    <%= f.text_field :lon, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :view %>
    <%= f.text_field :view, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary"%>
  
  
  <!-- <div class="field">
    <%= f.label "Youtube id" %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :view %><br>
    <%= f.number_field :view %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div> -->
<% end %>

test_1_geo_sock_update/app/views/videos/_init_socket.html.erb
 <script type='text/javascript'>
  window.realtime = {};
  window.realtime.messageQueue = [];
  window.realtime.enabled = false;
</script>


<script>

initSocket = function(){
  if (typeof io != 'undefined' && io != null) {
    window.realtime.token = '<%=@realtime_token%>';
    window.realtime.userId = '<%= @realtime_user_id %>';
    window.realtime.socketIo = io.connect('<%= @realtime_server_url %>/?_rtUserId=<%= @realtime_user_id %>&_rtToken=<%=@realtime_token%>');
  }
  
  if (window.realtime.socketIo) {
  
    window.realtime.enabled = true;
  
    window.realtime.socketIo.on('connect', function() {
      // Give a nice round-trip ACK to our realtime server that we connected.
        window.realtime.socketIo.emit('realtime_user_id_connected', { userId: window.realtime.userId, currentVideoId:<%= @video.id %> });
      });
  
    // Queue up all incoming realtime messages.
      window.realtime.socketIo.on('realtime_msg', function(message) {
        window.realtime.messageQueue.push(message);
    });
  }
  
  console.log(window)
  // optional: message_handler dequeues realtime messages into Backbone.js style events
  if (window.realtime.enabled) {
    window.realtime.eventBus = _.extend({}, Backbone.Events);
  
    messageQueueRunner = function() {
      message = window.realtime.messageQueue.shift();
      if (message) {
        window.realtime.eventBus.trigger('realtimeMessage', message);
      }
    };
    setInterval(messageQueueRunner, 100);
  }

}
</script>

test_1_geo_sock_update/app/views/videos/edit.html.erb
<h2 class="resource-header">Editing Video</h2>

<div class="col-xs-12">
  <div class="col-xs-1 col-sm-2 col-md-3 col-lg-4"></div>
  
  <div class="col-xs-10 col-sm-8 col-md-6 col-lg-4">
    <div class="panel panel-default">
      
      <div class="panel-heading">
        <h3 class="panel-title">Update Video</h3>
      </div>
      
      <div class="panel-body">
        <%= render 'form' %>
      </div>
      
    </div>
  </div>
  
  <div class="col-xs-1 col-sm-2 col-md-3 col-lg-4"></div>
</div>

<div style="clear: both"></div>
<hr/>
<div class="col-xs-12">
  <%= link_to 'Show', @video, class: "btn btn-primary" %> 
  <%= link_to 'Back', videos_path, class: "btn btn-warning" %>
</div>

test_1_geo_sock_update/app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="resource-header">Listing Videos</h2>
<div class="col-xs-12">
	<div class="col-xs-0 col-sm-1 col-md-2 col-lg-2">
	</div>
	<div class="col-xs-12 col-sm-10 col-md-8 col-lg-8">
		<table class="table table-striped table-hover">
		  <thead>
		    <tr>
			  <th>#</th>
		      <th>Name</th>
		      <th>Url</th>
		      <th>Lat</th>
		      <th>Lon</th>
		      <th colspan="2">View</th>
		    </tr>
		  </thead>
		
		  <tbody>
		    <% @videos.each_with_index do |video, index| %>
		      <tr>
		      	<td><%= index + 1 %></td>
		        <td><%= video.name %></td>
		        <td><%= video.url %></td>
		        <td><%= video.lat %></td>
		        <td><%= video.lon %></td>
		        <td><%= video.view %></td>
		        <td style="text-align: center;">
		        	<%= link_to 'Show', video, {class: "btn btn-info btn-xs", style: "text-decoration : none;"} %>
			        <%= link_to 'Edit', edit_video_path(video), {class: "btn btn-success btn-xs", style: "text-decoration : none;"} %>
			        <%= link_to "Map", "/videos/map?id=" + video.id.to_s, {class: "btn btn-primary btn-xs", style: "text-decoration : none;"} %>
			        <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs", style: "text-decoration : none;" %>
		        </td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
		<%= link_to 'New Video', new_video_path , class: "btn btn-default", style: "float: right;" %>
	</div>
	<div class="col-xs-0 col-sm-1 col-md-2 col-lg-2">
	</div>
</div>
<br>

test_1_geo_sock_update/app/views/videos/map.html.erb
<head>
 


<script src="<%= @realtime_server_url %>/socket.io/socket.io.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js"></script>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

 
<%= render 'init_socket' %>




</head>

<h2 class="resource-header">Map for video <%= @video.name %></h2>

<div class="col-xs-12">
  <div id="multi_markers" style='width: 100%; height: 600px;'></div>
</div>



<div style="clear:both;"></div>
<hr/>

<div class="col-xs-12">
  <%= link_to 'Back', videos_path, class: "btn btn-warning" %>
</div>



<script type='text/javascript'>
  
  $( document ).ready(function() {
    initSocket();   
      
    if (window.realtime.enabled && window.realtime.eventBus){
        // handle events in the queue with eventing
      var realtimeMessageEventConsoleLogger = function(message) {
        console.log(message);
        if(message.msg == "video_views_increase"){          
            markers = handler.addMarkers([{"lat": parseFloat(message.lat),"lng":parseFloat(message.lon)}]);
          }
      };
      window.realtime.eventBus.on('realtimeMessage', realtimeMessageEventConsoleLogger);
    
    } else if (window.realtime.enabled) {
      // handle events in the queue without eventing
      messageQueueConsoleLogger = function() {
        message = window.realtime.messageQueue.shift();
        if (message) {
          console.log(message);
        }
      };
      setInterval(messageQueueConsoleLogger, 100);
    
    } else {
      console.log('Error: Realtime was not enabled.');
      alert("Can't create socket... Please Refresh.")
    }
  });

  handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'multi_markers'}}, function(){
  var markers = handler.addMarkers([
    {
      lat: <%= @video.lat %>,
      lng: <%= @video.lat %>,
      picture: {
        url: "http://m.f29.img.vnecdn.net/2015/07/11/tham-an-Binh-Phuoc-8-7220-1436594654.jpg", // should change to others image url
        width:  36,
        height: 36
      },
      infowindow: "Uploader!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(2);
});






</script>

test_1_geo_sock_update/app/views/videos/new.html.erb
<h2 class="resource-header">New Video</h2>




<div class="col-xs-12">
  <div class="col-xs-1 col-sm-2 col-md-3 col-lg-4"></div>
  
  <div class="col-xs-10 col-sm-8 col-md-6 col-lg-4">
    <div class="panel panel-default">
      
      <div class="panel-heading">
        <h3 class="panel-title">Update Video</h3>
      </div>
      
      <div class="panel-body">
        <%= render 'form' %>
      </div>
      
    </div>
  </div>
  
  <div class="col-xs-1 col-sm-2 col-md-3 col-lg-4"></div>
</div>



<div style="clear:both;"></div>
<hr/>

<div class="col-xs-12">
  <%= link_to 'Back', videos_path, class: "btn btn-warning" %>
</div>

test_1_geo_sock_update/app/views/videos/show.html.erb
<head>
  <!-- required: realtime support framework -->

<script src="<%= @realtime_server_url %>/socket.io/socket.io.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js"></script>

<%= render "init_socket"%>
<%= 
  #javascript_include_tag "messages"
%>
</head>


<div class="col-xs-12">
  <h3 class="resource-header"> Video Detail: <%= @video.name %></h3>
</div>
<div class="col-xs-12">
  <p id="notice" style="margin-left: 40px;"><%= notice %></p>
</div>
<div class="col-xs-12">	
	
	<div class="col-xs-12 col-sm-4 col-md-4 col-lg-5">
	  <table class="table table-hover">
	    <tr>
        <td>Name: </td>
        <td><%= @video.name %></td>
      </tr>
      
       <tr>
        <td>Youtube Id: </td>
        <td><%= @video.url %></td>
      </tr>
      
       <tr>
        <td>Location: </td>
        <td><%= @video.lat.to_s + "/" + @video.lon.to_s %></td>
      </tr>
      
       <tr id="video-view-block">
        <td>View: </td>
        <td id="video-views"><%= @video.view %></td>
      </tr>
      
       <tr id="video-unique-view-block">
        <td>Unique View: </td>
        <td id="video-unique-views" ><%= @video.unique_view || 1 %></td>
      </tr>
	  </table>
	  
	</div>
	
	<div class="col-xs-12 col-sm-8 col-md-8 col-lg-7 text-center">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/<%=  @video.url %>" frameborder="0" allowfullscreen></iframe>
	</div>	
</div>

<div style="clear:both;"></div>
<hr/>

<div class="col-xs-12">
  <%= link_to 'Edit', edit_video_path(@video), class: "btn btn-primary" %> 
  <%= link_to 'Back', videos_path, class: "btn btn-warning" %>
</div>


<br/>