test_1_geo_sock_update/config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  get 'chats/room'
  get 'sessions/new'
  get 'sessions/create'

  get "videos/map"
  
  get "messages/read/:id(.:format)" => "messages#read"
  post "messages/read/:id(.:format)" => "messages#read"
  
  
  get '/login' => 'sessions#new'#, #:as => :login
  post '/login' => 'sessions#create'#, #:as => :login
  
  get '/chatroom' => 'chats#room'#, :as => :chat
  post '/chatroom' => 'chats#room'#, :as => :chat
  
  
  get '/redis-messages/:key(.:format)' => 'redis_messages#show'
  delete '/redis-messages/:key(.:format)' => 'redis_messages#destroy'
  post '/redis-messages' => 'redis_messages#create'
  post '/redis-messages/read' => 'redis_messages#read'

  
  resources :messages
  resources :videos
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :media_contents, only: [:create]
  

  root 'chats#room'

end

test_1_geo_sock_update/app/models/resume.rb
class Resume < ActiveRecord::Base
  
  mount_uploader :attachment, AttachmentUploader 
  validates :name, presence: true

end

test_1_geo_sock_update/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)
    
    if @resume.save
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been saved"
    else 
      render "new"
    end    
  end
  
  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice: "The resume #{@resume.name} has beed destroyed"
  end

  private
  def resume_params
    params.require(:resume).permit(:name, :attachment)
  end
end

test_1_geo_sock_update/app/helpers/resumes_helper.rb
module ResumesHelper
end

test_1_geo_sock_update/app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

test_1_geo_sock_update/app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

test_1_geo_sock_update/app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>  
<%end%>

<br />

<%= link_to "New Resume", new_resume_path, class: "btn btn-primary"%>
<br />
<br />

<form action="/media_contents" class="dropzone">
  <div class="fallback">
    <input name="name" type="hidden" value="This auto upload">
    <input name="file" type="file" />
  </div>
</form>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>&nbsp</th>
    </tr>
  </thead>
  
  <tbody>
    
    <% @resumes.each do |resume| %>
    <tr>
      <td><%= resume.name%></td>
      <td><%= link_to "Download Resume", resume.attachment_url%></td>
      <td><%= button_to "Delete", resume, method: :delete, class: "btn btn-danger", confirm: "Are you wanna do that ?"%></td>
    </tr>
    <% end %>
    
  </tbody>
  
</table>

test_1_geo_sock_update/app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
  
  <div class="alert alert-error">
    <ul>
      <% @resume.errors.full_messages.each do |messge| %>
        <li> <% message %> </li>
      <% end %>
    </ul>
  </div>
  
<% end  %>


<div class="well">
  
  <%= form_for @resume, html: {multipart: true} do |f |%>
    
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :attachment%>
    <%= f.file_field :attachment%>
    
    <%= f.submit "Save", class: "btn btn-primary"%>
    
  <%end%>
  
</div>