test_1_geo_sock_update/config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  get 'chats/room'
  get 'sessions/new'
  get 'sessions/create'

  get "videos/map"
  
  get "messages/read/:id(.:format)" => "messages#read"
  post "messages/read/:id(.:format)" => "messages#read"
  
  
  get '/login' => 'sessions#new'#, #:as => :login
  post '/login' => 'sessions#create'#, #:as => :login
  
  get '/chatroom' => 'chats#room'#, :as => :chat
  post '/chatroom' => 'chats#room'#, :as => :chat
  
  
  get '/redis-messages/:key(.:format)' => 'redis_messages#show'
  delete '/redis-messages/:key(.:format)' => 'redis_messages#destroy'
  post '/redis-messages' => 'redis_messages#create'
  post '/redis-messages/read' => 'redis_messages#read'

  
  resources :messages
  resources :videos
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :media_contents, only: [:create]
  

  root 'chats#room'

end

test_1_geo_sock_update/app/models/message.rb
class Message < ActiveRecord::Base
  
  def self.clear_expired_message
      Message.where("expired <= (DATETIME('now'))").destroy_all
  end
  
end

test_1_geo_sock_update/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include MessagesHelper
  
  before_action :set_message, only: [:show, :edit, :update, :destroy, :read]
  skip_before_filter :verify_authenticity_token


  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # Client will defined when it read or not ?! 
  # That's mean Show is not read.
  # We need Id of read message to process it
  # GET /messages/read/10.json
  # POST /messages/read/10.json
  def read
    message_id = params[:id]
    read = @message.read
    unless @message.read
      @message.read = true
      @message.expired = DateTime.now + 12.hours
      @message.save
    end    
    
    respond_to do |format|
      if !read
        format.html { redirect_to @message, notice: 'Accepted.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @message, notice: 'Accepted.' }
        format.json { head :no_content }
      end
    end
    
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    # destroy_all
    # When we create new message that same with reply ... So delete all chatmate message.
    delete_chatmate_message message_params
    create_params = init_message_record message_params
    @message = Message.new(create_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:from, :to, :content, :expired, :read, :reply)
    end
end

test_1_geo_sock_update/app/helpers/messages_helper.rb
module MessagesHelper
  
  def init_message_record message_params
    create_params = message_params.clone
    create_params[:expired] = DateTime.now + 12.days
    create_params[:read] = false
    create_params[:reply] = false
    
    create_params
  end
  
  
  def delete_chatmate_message message_params
    chat_mate_id = message_params[:to]
    chatter = message_params[:from]
    Message.destroy_all(from: chat_mate_id, to: chatter) 
    
  end
  
end

test_1_geo_sock_update/app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :from %>
    <%= f.text_field :from, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :to %>
    <%= f.text_field :to, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  
  
  <div class="actions">
    <%= f.submit  class: "btn btn-primary" %>
  </div>
<% end %>

test_1_geo_sock_update/app/views/messages/edit.html.erb
<h2 class="resource-header">Edit Message</h2>

<div class="col-xs-12">
  <div class="col-xs-1 col-sm-2 col-md-3 col-lg-4"></div>
  
  <div class="col-xs-10 col-sm-8 col-md-6 col-lg-4">
    <div class="panel panel-default">
      
      <div class="panel-heading">
        <h3 class="panel-title">Update Message</h3>
      </div>
      
      <div class="panel-body">
        <%= render 'form' %>
      </div>
      
    </div>
  </div>
  
  <div class="col-xs-1 col-sm-2 col-md-3 col-lg-4"></div>
</div>



<div style="clear:both;"></div>
<hr/>

<div class="col-xs-12">
  <%= link_to 'Show', @message, class: "btn btn-warning"  %> 
  <%= link_to 'Back', messages_path, class: "btn btn-warning"  %>
</div>

test_1_geo_sock_update/app/views/messages/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Content</th>
      <th>Expired</th>
      <th>Read</th>
      <th>Reply</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.from %></td>
        <td><%= message.to %></td>
        <td><%= message.content %></td>
        <td><%= message.expired %></td>
        <td><%= message.read %></td>
        <td><%= message.reply %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %> -->

<p id="notice"><%= notice %></p>

<h2 class="resource-header">Listing Message</h2>
<div class="col-xs-12">
  <div class="col-xs-0 col-sm-1 col-md-2 col-lg-2">
  </div>
  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-8">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>#Id</th>
          <th>From</th>
          <th>To</th>
          <th>Content</th>
          <th>Expired</th>
          <th>Read</th>
          <th>Reply</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
      <% @messages.each do |message| %>
          <tr>
            <td><%= message.id %></td>
            <td><%= message.from %></td>
            <td><%= message.to %></td>
            <td><%= message.content %></td>
            <td><%= message.expired %></td>
            <td><%= message.read %></td>
            <td><%= message.reply %></td>
            <td style="text-align: center;">
              <%= link_to 'Show', message, {class: "btn btn-info btn-xs", style: "text-decoration : none;"} %>
              <%= link_to 'Read', "/messages/read/" + message.id.to_s, {class: "btn btn-success btn-xs", style: "text-decoration : none;"} %>
              <%= link_to 'Edit', edit_message_path(message), {class: "btn btn-success btn-xs", style: "text-decoration : none;"} %>
              <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs", style: "text-decoration : none;" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Message', new_message_path , class: "btn btn-default", style: "float: right;" %>
  </div>
  <div class="col-xs-0 col-sm-1 col-md-2 col-lg-2">
  </div>
</div>
<br>

test_1_geo_sock_update/app/views/messages/new.html.erb
<h2 class="resource-header">New Message</h2>

<div class="col-xs-12">
  <div class="col-xs-1 col-sm-2 col-md-3 col-lg-4"></div>
  
  <div class="col-xs-10 col-sm-8 col-md-6 col-lg-4">
    <div class="panel panel-default">
      
      <div class="panel-heading">
        <h3 class="panel-title">Update Video</h3>
      </div>
      
      <div class="panel-body">
        <%= render 'form' %>
      </div>
      
    </div>
  </div>
  
  <div class="col-xs-1 col-sm-2 col-md-3 col-lg-4"></div>
</div>



<div style="clear:both;"></div>
<hr/>

<div class="col-xs-12">
  <%= link_to 'Back', messages_path, class: "btn btn-warning" %>
</div>

test_1_geo_sock_update/app/views/messages/show.html.erb
<div class="col-xs-12">
  <h3 class="resource-header"> Message #<%= @message.id %></h3>
</div>
<div class="col-xs-12">
  <p id="notice" style="margin-left: 40px;"><%= notice %></p>
</div>
<div class="col-xs-12"> 
  <div class="col-xs-0 col-sm-4 col-md-4 col-lg-4"> </div>
  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
    <table class="table table-hover">
      <tr>
        <td>From: </td>
        <td><%= @message.from %></td>
      </tr>
      
       <tr>
        <td>To: </td>
        <td><%= @message.to %></td>
      </tr>
      
       <tr>
        <td>Content: </td>
        <td><%= @message.content %></td>
      </tr>
      
      <tr>
        <td>Expired </td>
        <td><%= @message.expired.to_s %></td>
      </tr>
      
      <tr>
        <td>Read?: </td>
        <td><%= @message.read %></td>
      </tr>
      
      <tr>
        <td>Reply: </td>
        <td><%= @message.reply %></td>
      </tr>
      
    </table>
    
  </div>
  <div class="col-xs-0 col-sm-4 col-md-4 col-lg-4"> </div>

</div>

<div style="clear:both;"></div>
<hr/>

<div class="col-xs-12">
  <%= link_to 'Edit', edit_message_path(@message), class: "btn btn-primary" %> 
  <%= link_to 'Back', messages_path, class: "btn btn-warning" %>
</div>


<br/>